name: DevSu Django CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Build, Test & Code Snalysis
    runs-on: ubuntu-latest

    env:
        DEBUG: 1
        DJANGO_SECRET_KEY: ^gd^u-6@jc!i(2aw9a4u)j%wt7of693&1qro^kym&=7@5n&py=
        DJANGO_ALLOWED_HOSTS: localhost
        DATABASE_NAME: db.sqlite3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage flake8

      - name: Run static code analysis
        run: |
          flake8 .

      - name: Run unit tests
        run: |
          coverage run manage.py test
          coverage report

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest

  security-scan:
    needs: docker
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.64.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.64.1_Linux-64bit.deb


      - name: Scan Docker image for vulnerabilities
        run: trivy image ${{ secrets.DOCKER_USERNAME }}/django-app:latest